version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: flask_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/mydatabase
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: ["gunicorn", "--reload","-w", "2", "-b", "0.0.0.0:5000", "app.main:app"]

  frontend:
    dns:
    - 8.8.8.8
    - 8.8.4.4
    build: ./frontend
    container_name: nextjs_frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:5000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  postgres_data: